"""
reporter.py — Module 4
Opens ONE GitHub issue per finding (max 3 issues per repo).
Focused single-finding issues get triaged. Walls of findings get closed.
"""

from github import Github, GithubException
from config import GITHUB_TOKEN


gh = Github(GITHUB_TOKEN)

SEVERITY_EMOJI = {
    "critical": "🔴",
    "high":     "🟠",
    "medium":   "🟡",
    "low":      "🔵",
}

TYPE_EMOJI = {
    "bug":      "🐛",
    "security": "🔒",
}

MAX_ISSUES_PER_REPO = 3   # Never open more than this many issues on one repo


def format_single_issue_body(finding: dict, repo_name: str) -> str:
    """Formats a single finding into a clean, focused issue body."""
    sev     = finding.get("severity", "medium")
    ftype   = finding.get("type", "bug")
    s_emoji = SEVERITY_EMOJI.get(sev, "⚪")
    t_emoji = TYPE_EMOJI.get(ftype, "🔍")

    return f"""{t_emoji} **{ftype.capitalize()}** · {s_emoji} {sev.capitalize()} · Confidence: {int(finding.get('confidence', 0) * 100)}%

**File:** `{finding.get('file_path', 'Unknown')}`
**Location:** `{finding.get('line_reference', 'N/A')}`

---

### What's wrong

{finding.get('description', 'No description provided.')}

### Suggested fix

{finding.get('fix', 'No fix provided.')}

---

<details>
<summary>About this report</summary>

This finding was generated by an automated audit tool using Llama 3.3 70B + verification passes.
Only findings with ≥92% confidence that passed both LLM self-verification and line reference
verification are reported. False positives are still possible — please verify before acting.

</details>"""


def open_issues(repo_full_name: str, findings: list[dict]) -> list[str]:
    """
    Opens one GitHub issue per finding, up to MAX_ISSUES_PER_REPO.
    Only opens issues for medium+ severity findings.
    Returns list of issue URLs opened.
    """
    if not findings:
        print(f"[Reporter] No findings for {repo_full_name} — skipping.")
        return []

    # Only report medium+ severity
    significant = [
        f for f in findings
        if f.get("severity") in ("critical", "high", "medium")
    ]

    if not significant:
        print(f"[Reporter] Only low-severity findings for {repo_full_name} — skipping.")
        return []

    # Cap at MAX_ISSUES_PER_REPO — take highest severity first
    to_report = significant[:MAX_ISSUES_PER_REPO]

    print(f"[Reporter] Opening {len(to_report)} issue(s) on {repo_full_name} "
          f"(capped from {len(significant)} significant findings)...")

    try:
        repo = gh.get_repo(repo_full_name)
    except GithubException as e:
        print(f"[Reporter] Could not access repo {repo_full_name} → {e}")
        return []

    issue_urls = []

    for finding in to_report:
        sev     = finding.get("severity", "medium")
        ftype   = finding.get("type", "bug")
        title   = f"🤖 {TYPE_EMOJI.get(ftype, '🔍')} {finding.get('title', 'Potential issue found')}"
        body    = format_single_issue_body(finding, repo_full_name)

        try:
            issue = repo.create_issue(title=title, body=body)
            print(f"[Reporter] ✅ Issue opened → {issue.html_url}")
            issue_urls.append(issue.html_url)

        except GithubException as e:
            if e.status == 410:
                print(f"[Reporter] Issues disabled on {repo_full_name} — stopping.")
                break
            elif e.status == 403:
                print(f"[Reporter] No permission to open issues on {repo_full_name} — stopping.")
                break
            else:
                print(f"[Reporter] GitHub error → {e.status}: {e.data}")
        except Exception as e:
            print(f"[Reporter] Unexpected error → {e}")

    return issue_urls


# ── Quick test ───────────────────────────────────────────────
if __name__ == "__main__":
    sample = {
        "type":           "security",
        "severity":       "critical",
        "confidence":     0.97,
        "line_reference": "get_user",
        "title":          "SQL injection via f-string in get_user()",
        "description":    "User input is directly interpolated into an SQL query: `query = f\"SELECT * FROM users WHERE username = '{username}'\"`.",
        "fix":            "Use parameterized queries: `cursor.execute('SELECT * FROM users WHERE username = ?', (username,))`",
        "file_path":      "src/db.py",
        "language":       "Python",
    }
    body = format_single_issue_body(sample, "example/repo")
    print(body)
